// Generated by scripts/build-user-docs.js — do not edit by hand.

export interface UserDocSection {
  id: string
  title: string
  level: number
}
export interface UserDocManifestEntry {
  title: string
  summary: string
  sectionIds: string[]
  sections: UserDocSection[]
}
export type UserDocManifest = Record<string, UserDocManifestEntry>

export const userDocsManifest: UserDocManifest = {
  concepts: {
    title: 'Key Concepts',
    summary: 'Details regarding the core concepts that the Cortex app is comprised of.',
    sectionIds: ['key-concepts', 'connections-planned'],
    sections: [
      {
        id: 'key-concepts',
        title: 'Key Concepts',
        level: 1,
      },
      {
        id: 'connections-planned',
        title: 'Connections (planned)',
        level: 2,
      },
    ],
  },
  'getting-started': {
    title: 'Getting Started',
    summary:
      'Get Cortex running, then go to Home, Chat, or Settings. Chat is where you talk to the AI; Settings is where you configure providers and models.',
    sectionIds: ['getting-started', 'run-cortex', 'main-areas', 'next-steps'],
    sections: [
      {
        id: 'getting-started',
        title: 'Getting Started',
        level: 1,
      },
      {
        id: 'run-cortex',
        title: 'Run Cortex',
        level: 2,
      },
      {
        id: 'main-areas',
        title: 'Main areas',
        level: 2,
      },
      {
        id: 'next-steps',
        title: 'Next steps',
        level: 2,
      },
    ],
  },
  vision: {
    title: 'What is Cortex?',
    summary:
      'Cortex is an AI-powered personal knowledge management system that transforms how you interact with your own data. It connects your information into a unified, intelligent platform that helps you understand patterns, surface insights, and maintain context across your digital life.',
    sectionIds: [
      'what-is-cortex',
      'core-benefits',
      'own-your-data-completely',
      'privacy-first-intelligence',
      'active-knowledge-management',
      'transparent-ai-understanding',
      'how-it-works',
      'local-first-architecture',
      'intelligent-data-integration',
      'flexible-ai-processing',
      'progressive-evolution',
      'the-bigger-vision',
    ],
    sections: [
      {
        id: 'what-is-cortex',
        title: 'What is Cortex?',
        level: 1,
      },
      {
        id: 'core-benefits',
        title: 'Core Benefits',
        level: 2,
      },
      {
        id: 'own-your-data-completely',
        title: 'Own Your Data Completely',
        level: 3,
      },
      {
        id: 'privacy-first-intelligence',
        title: 'Privacy-First Intelligence',
        level: 3,
      },
      {
        id: 'active-knowledge-management',
        title: 'Active Knowledge Management',
        level: 3,
      },
      {
        id: 'transparent-ai-understanding',
        title: 'Transparent AI Understanding',
        level: 3,
      },
      {
        id: 'how-it-works',
        title: 'How It Works',
        level: 2,
      },
      {
        id: 'local-first-architecture',
        title: 'Local-First Architecture',
        level: 3,
      },
      {
        id: 'intelligent-data-integration',
        title: 'Intelligent Data Integration',
        level: 3,
      },
      {
        id: 'flexible-ai-processing',
        title: 'Flexible AI Processing',
        level: 3,
      },
      {
        id: 'progressive-evolution',
        title: 'Progressive Evolution',
        level: 3,
      },
      {
        id: 'the-bigger-vision',
        title: 'The Bigger Vision',
        level: 2,
      },
    ],
  },
} as UserDocManifest

const docBodies: Record<string, string> = {}
const docSections: Record<
  string,
  Array<{ id: string; title: string; content: string }>
> = {}

docBodies['concepts'] = `# Key Concepts

## Connections (planned)

**Planned.** Connections are not yet available in the app. The following describes how they are intended to work once implemented.

A **connection** is a **data source** you can connect to the app—for example a folder on your computer or a cloud service (e.g. Slack, Google Drive). The app can read from and write to a connection so that agents can use that data (within the permissions you set) and so that data from different sources can be brought together into your knowledge graph.

You would create **connection instances** (e.g. “My Project Folder”, “Work Slack”) and control what agents can do per connection in your **permission mode** (allow, ask, or deny read/write per connection type and per instance). The first connection type we plan to support is **Local Folder**: a folder on your system, including all subfolders and files, with agent tools to list, read, and write files within that folder.`
docSections['concepts'] = [
  { id: 'key-concepts', title: 'Key Concepts', content: `` },
  {
    id: 'connections-planned',
    title: 'Connections (planned)',
    content: `**Planned.** Connections are not yet available in the app. The following describes how they are intended to work once implemented.

A **connection** is a **data source** you can connect to the app—for example a folder on your computer or a cloud service (e.g. Slack, Google Drive). The app can read from and write to a connection so that agents can use that data (within the permissions you set) and so that data from different sources can be brought together into your knowledge graph.

You would create **connection instances** (e.g. “My Project Folder”, “Work Slack”) and control what agents can do per connection in your **permission mode** (allow, ask, or deny read/write per connection type and per instance). The first connection type we plan to support is **Local Folder**: a folder on your system, including all subfolders and files, with agent tools to list, read, and write files within that folder.`,
  },
]

docBodies['getting-started'] = `# Getting Started

## Run Cortex

Start the app from your terminal or by opening the application. The first time you open Cortex, you'll see the Home view.

## Main areas

- **Home** — Overview and quick access. Use the sidebar to switch views.
- **Chat** — Have conversations with the AI. Choose a model and start typing. Responses stream in and support markdown and code.
- **Settings** — Configure AI providers (e.g. Ollama, Anthropic), select models, and adjust appearance (theme).

## Next steps

- Read [What is Cortex?](vision.md) for the big picture.
- Open **Settings** to add a provider and pick a model, then try **Chat**.`
docSections['getting-started'] = [
  { id: 'getting-started', title: 'Getting Started', content: `` },
  {
    id: 'run-cortex',
    title: 'Run Cortex',
    content: `Start the app from your terminal or by opening the application. The first time you open Cortex, you'll see the Home view.`,
  },
  {
    id: 'main-areas',
    title: 'Main areas',
    content: `- **Home** — Overview and quick access. Use the sidebar to switch views.
- **Chat** — Have conversations with the AI. Choose a model and start typing. Responses stream in and support markdown and code.
- **Settings** — Configure AI providers (e.g. Ollama, Anthropic), select models, and adjust appearance (theme).`,
  },
  {
    id: 'next-steps',
    title: 'Next steps',
    content: `- Read [What is Cortex?](vision.md) for the big picture.
- Open **Settings** to add a provider and pick a model, then try **Chat**.`,
  },
]

docBodies['vision'] = `# What is Cortex?

Cortex is an AI-powered personal knowledge management system that transforms how you interact with your own data. It connects all your personal information (conversations, health metrics, activities, projects, places, and experiences) into a unified, intelligent platform that helps you understand patterns, surface insights, and maintain meaningful context across your entire digital life.

## Core Benefits

### Own Your Data Completely
- All data stored locally in human-readable formats (Markdown, JSON)
- Never locked into proprietary systems or cloud services
- Full control over what stays private and what you choose to share
- Your knowledge base travels with you, forever

### Privacy-First Intelligence
- AI processing happens locally on your machine by default
- You decide which tasks can use cloud AI based on your own privacy preferences
- Sensitive personal data never leaves your control unless you explicitly choose otherwise
- Flexibility to balance privacy, speed, and capability for each use case

### Active Knowledge Management
- Beyond passive storage, the system proactively surfaces patterns and connections
- AI agents notice insights you might miss and bring them to your attention
- User-driven exploration through natural language chat and visual interfaces
- Both modes working together: ask questions AND receive unprompted discoveries

### Transparent AI Understanding
- The graph database makes the AI's "mental model" visible and inspectable
- See exactly what relationships and context informed any suggestion
- Audit how the AI understands your data
- Correct misunderstandings by fixing source data or transformation logic
- No black-box AI decisions, everything is traceable and editable

## How It Works

### Local-First Architecture
Cortex is built on a foundation of **local-first computing**. Your data lives in open, portable formats on your own machine. The graph database acts as an intelligent index, completely disposable and rebuildable from your source files.

This means:
- Work offline whenever you want
- Complete data sovereignty
- Version control and backup on your terms
- No vendor lock-in, ever

### Intelligent Data Integration
The system connects multiple data sources while respecting the nature of each:
- **Local data** (notes, journals, documents) → Direct local storage
- **External services** (Strava, GitHub, health apps) → Sync to local, then index
- **The Integration Heuristic**: "Would I want to reference this in my Notes?"
  - Yes → Create a Markdown file (meaningful events, insights)
  - No → Store as structured data (metrics, logs, continuous streams)

### Flexible AI Processing
By default, AI analysis runs locally to preserve privacy. You have full control to:
- Keep sensitive data processing entirely local
- Use cloud AI for specific tasks where you want more capability or speed
- Define your own boundaries based on your use cases and comfort level
- Change these preferences at any time

### Progressive Evolution
Cortex starts simple and grows smarter over time:
- Begin with manual exploration through chat and visual interfaces
- System learns which patterns you care about
- Agents gradually automate repetitive insights
- Both the data model and the tooling improve continuously through use

## The Bigger Vision

Beyond being a personal knowledge tool, Cortex represents a new approach to AI-augmented development. The long-term goal is a system where:
- AI agents become co-developers, not just assistants
- New features emerge from conversational guidance
- The system improves its own architecture over time
- You focus on "what" and "why" while AI handles "how"

But first, we build an excellent manual experience that proves the value, then we automate what works.

---

*This vision guides all architectural and implementation decisions. When in doubt, return to these principles: data ownership, privacy by default, user agency, and transparent intelligence.*`
docSections['vision'] = [
  {
    id: 'what-is-cortex',
    title: 'What is Cortex?',
    content: `Cortex is an AI-powered personal knowledge management system that transforms how you interact with your own data. It connects all your personal information (conversations, health metrics, activities, projects, places, and experiences) into a unified, intelligent platform that helps you understand patterns, surface insights, and maintain meaningful context across your entire digital life.`,
  },
  { id: 'core-benefits', title: 'Core Benefits', content: `` },
  {
    id: 'own-your-data-completely',
    title: 'Own Your Data Completely',
    content: `- All data stored locally in human-readable formats (Markdown, JSON)
- Never locked into proprietary systems or cloud services
- Full control over what stays private and what you choose to share
- Your knowledge base travels with you, forever`,
  },
  {
    id: 'privacy-first-intelligence',
    title: 'Privacy-First Intelligence',
    content: `- AI processing happens locally on your machine by default
- You decide which tasks can use cloud AI based on your own privacy preferences
- Sensitive personal data never leaves your control unless you explicitly choose otherwise
- Flexibility to balance privacy, speed, and capability for each use case`,
  },
  {
    id: 'active-knowledge-management',
    title: 'Active Knowledge Management',
    content: `- Beyond passive storage, the system proactively surfaces patterns and connections
- AI agents notice insights you might miss and bring them to your attention
- User-driven exploration through natural language chat and visual interfaces
- Both modes working together: ask questions AND receive unprompted discoveries`,
  },
  {
    id: 'transparent-ai-understanding',
    title: 'Transparent AI Understanding',
    content: `- The graph database makes the AI's "mental model" visible and inspectable
- See exactly what relationships and context informed any suggestion
- Audit how the AI understands your data
- Correct misunderstandings by fixing source data or transformation logic
- No black-box AI decisions, everything is traceable and editable`,
  },
  { id: 'how-it-works', title: 'How It Works', content: `` },
  {
    id: 'local-first-architecture',
    title: 'Local-First Architecture',
    content: `Cortex is built on a foundation of **local-first computing**. Your data lives in open, portable formats on your own machine. The graph database acts as an intelligent index, completely disposable and rebuildable from your source files.

This means:
- Work offline whenever you want
- Complete data sovereignty
- Version control and backup on your terms
- No vendor lock-in, ever`,
  },
  {
    id: 'intelligent-data-integration',
    title: 'Intelligent Data Integration',
    content: `The system connects multiple data sources while respecting the nature of each:
- **Local data** (notes, journals, documents) → Direct local storage
- **External services** (Strava, GitHub, health apps) → Sync to local, then index
- **The Integration Heuristic**: "Would I want to reference this in my Notes?"
  - Yes → Create a Markdown file (meaningful events, insights)
  - No → Store as structured data (metrics, logs, continuous streams)`,
  },
  {
    id: 'flexible-ai-processing',
    title: 'Flexible AI Processing',
    content: `By default, AI analysis runs locally to preserve privacy. You have full control to:
- Keep sensitive data processing entirely local
- Use cloud AI for specific tasks where you want more capability or speed
- Define your own boundaries based on your use cases and comfort level
- Change these preferences at any time`,
  },
  {
    id: 'progressive-evolution',
    title: 'Progressive Evolution',
    content: `Cortex starts simple and grows smarter over time:
- Begin with manual exploration through chat and visual interfaces
- System learns which patterns you care about
- Agents gradually automate repetitive insights
- Both the data model and the tooling improve continuously through use`,
  },
  {
    id: 'the-bigger-vision',
    title: 'The Bigger Vision',
    content: `Beyond being a personal knowledge tool, Cortex represents a new approach to AI-augmented development. The long-term goal is a system where:
- AI agents become co-developers, not just assistants
- New features emerge from conversational guidance
- The system improves its own architecture over time
- You focus on "what" and "why" while AI handles "how"

But first, we build an excellent manual experience that proves the value, then we automate what works.

---

*This vision guides all architectural and implementation decisions. When in doubt, return to these principles: data ownership, privacy by default, user agency, and transparent intelligence.*`,
  },
]

/** Full markdown body for a doc. */
export function getDocBody(slug: string): string | undefined {
  return docBodies[slug]
}

/** Short summary for tooltips (from frontmatter). */
export function getDocSummary(slug: string): string | undefined {
  return userDocsManifest[slug]?.summary
}

/** Section content (markdown) for a doc; for modal or deep link. */
export function getDocSectionContent(
  slug: string,
  sectionId: string
): string | undefined {
  const list = docSections[slug]
  if (!list) return undefined
  const s = list.find(x => x.id === sectionId)
  return s?.content
}

/** Ordered list of slugs for TOC. */
export const userDocSlugs: string[] = ['concepts', 'getting-started', 'vision']
