// Generated by scripts/build-user-docs.js — do not edit by hand.

export interface UserDocSection {
  id: string
  title: string
  level: number
}
export interface UserDocManifestEntry {
  title: string
  summary: string
  sectionIds: string[]
  sections: UserDocSection[]
}
export type UserDocManifest = Record<string, UserDocManifestEntry>

export const userDocsManifest: UserDocManifest = {
  concepts: {
    title: 'Key Concepts',
    summary: 'Details regarding the core concepts that the Cortex app is comprised of.',
    sectionIds: [
      'key-concepts',
      'connections',
      'what-counts-as-a-connection',
      'capabilities',
      'what-is-not-a-connection',
      'types',
      'permission-system',
      'summary',
    ],
    sections: [
      {
        id: 'key-concepts',
        title: 'Key Concepts',
        level: 1,
      },
      {
        id: 'connections',
        title: 'Connections',
        level: 2,
      },
      {
        id: 'what-counts-as-a-connection',
        title: 'What counts as a connection',
        level: 3,
      },
      {
        id: 'capabilities',
        title: 'Capabilities',
        level: 3,
      },
      {
        id: 'what-is-not-a-connection',
        title: 'What is not a connection',
        level: 3,
      },
      {
        id: 'types',
        title: 'Types',
        level: 2,
      },
      {
        id: 'permission-system',
        title: 'Permission system',
        level: 2,
      },
      {
        id: 'summary',
        title: 'Summary',
        level: 2,
      },
    ],
  },
  'getting-started': {
    title: 'Getting Started',
    summary:
      'Get Cortex running, then go to Home, Chat, or Settings. Chat is where you talk to the AI; Settings is where you configure providers and models.',
    sectionIds: ['getting-started', 'run-cortex', 'main-areas', 'next-steps'],
    sections: [
      {
        id: 'getting-started',
        title: 'Getting Started',
        level: 1,
      },
      {
        id: 'run-cortex',
        title: 'Run Cortex',
        level: 2,
      },
      {
        id: 'main-areas',
        title: 'Main areas',
        level: 2,
      },
      {
        id: 'next-steps',
        title: 'Next steps',
        level: 2,
      },
    ],
  },
  vision: {
    title: 'What is Cortex?',
    summary:
      'Cortex is an AI-powered personal knowledge management system that transforms how you interact with your own data. It connects your information into a unified, intelligent platform that helps you understand patterns, surface insights, and maintain context across your digital life.',
    sectionIds: [
      'what-is-cortex',
      'core-benefits',
      'own-your-data-completely',
      'privacy-first-intelligence',
      'active-knowledge-management',
      'transparent-ai-understanding',
      'how-it-works',
      'local-first-architecture',
      'intelligent-data-integration',
      'flexible-ai-processing',
      'progressive-evolution',
      'the-bigger-vision',
    ],
    sections: [
      {
        id: 'what-is-cortex',
        title: 'What is Cortex?',
        level: 1,
      },
      {
        id: 'core-benefits',
        title: 'Core Benefits',
        level: 2,
      },
      {
        id: 'own-your-data-completely',
        title: 'Own Your Data Completely',
        level: 3,
      },
      {
        id: 'privacy-first-intelligence',
        title: 'Privacy-First Intelligence',
        level: 3,
      },
      {
        id: 'active-knowledge-management',
        title: 'Active Knowledge Management',
        level: 3,
      },
      {
        id: 'transparent-ai-understanding',
        title: 'Transparent AI Understanding',
        level: 3,
      },
      {
        id: 'how-it-works',
        title: 'How It Works',
        level: 2,
      },
      {
        id: 'local-first-architecture',
        title: 'Local-First Architecture',
        level: 3,
      },
      {
        id: 'intelligent-data-integration',
        title: 'Intelligent Data Integration',
        level: 3,
      },
      {
        id: 'flexible-ai-processing',
        title: 'Flexible AI Processing',
        level: 3,
      },
      {
        id: 'progressive-evolution',
        title: 'Progressive Evolution',
        level: 3,
      },
      {
        id: 'the-bigger-vision',
        title: 'The Bigger Vision',
        level: 2,
      },
    ],
  },
} as UserDocManifest

const docBodies: Record<string, string> = {}
const docSections: Record<
  string,
  Array<{ id: string; title: string; content: string }>
> = {}

docBodies['concepts'] = `# Key Concepts

## Connections

A **connection** is a **data source** that the application can read from and write to. Data from connections is used to build or update the app’s knowledge graph(s); updates can also be written back to the connection. Connections are not the graph store itself.

### What counts as a connection

- **Local**: A folder on the system, or an app/process on the system that exposes data.
- **External/cloud**: A cloud or remote service (e.g. Slack, Google Drive, a REST API, Notion) that the user configures (credentials, endpoint, workspace, etc.).

### Capabilities

- **Read**: Ingest or sync data from the connection into the knowledge graph(s). For external sources, we first **extract and localize** the data in a format that involves the bare minimum transformation—ideally none. How that localized data gets into the graph is defined via **Types** (see below).
- **Write**: Update or sync data back to the connection (e.g. push notes, sync state). Connections are inherently read+write capable; permissions and UX control which of read/write (or both) are allowed for a given connection or tool.

### What is not a connection

- **Neo4j** is the **built-in graph database**. It is where graph data lives inside the app, not an external “source” in the connection sense. It does **not** fit the definition of a connection.
- **Which graphs (Neo4j DBs) an agent can use** is a **separate concept**: graph-level or knowledge-graph-level access control. That should be documented and designed alongside the permission system but under a different heading (e.g. “Graph access” or “Knowledge graph access”), not under “Connections.”

## Types

Getting data from a connection into the graph is governed by **Types**.

- **Type**: The user’s way to define **node (label) structures** for the graph—properties, indexes, and constraints. A Type describes a kind of node (e.g. Person, Location, Book).
- **Source**: A Type can have one or more **sources**. Each source binds to a **connection** and defines:
  - The **rule for import** (how to interpret or select data from that connection).
  - **Property mapping** (connection fields → node properties).

So: **Connection** (data source, read/write) → **Type** (node shape + optional sources) → **Source** (connection + import rule + property mapping) → **Graph**. A Type can source data from multiple connections; the Type and its sources define how that becomes graph nodes.

## Permission system

- **Connection type**: The kind of data source (e.g. Folder, Slack, Google Drive). Not Neo4j.
- **Connection**: A specific instance (e.g. “My Project Folder”, “Slack #general”, “Drive – Work”).
- **Tools** that operate on a connection are associated with a **connection type** and optionally a **connection** (instance). Permission hierarchy (in modes) remains: **category** → **connection type** → **connection** → **tool**, but only for tools that act on connections (data sources). Neo4j/graph tools are governed by **graph access** (and category), not by connection type/connection.

## Summary

- **Connections** = data sources (folder, app, cloud). Read: extract/localize with minimal transformation; path to graph is via **Types** (node structures) and **Source** (connection + import rule + property mapping). Write: sync back to the connection.
- **Neo4j** = built-in graph DB; not a connection. **Graph access** (which knowledge graphs agents can use) is a separate concept.`
docSections['concepts'] = [
  { id: 'key-concepts', title: 'Key Concepts', content: `` },
  {
    id: 'connections',
    title: 'Connections',
    content: `A **connection** is a **data source** that the application can read from and write to. Data from connections is used to build or update the app’s knowledge graph(s); updates can also be written back to the connection. Connections are not the graph store itself.`,
  },
  {
    id: 'what-counts-as-a-connection',
    title: 'What counts as a connection',
    content: `- **Local**: A folder on the system, or an app/process on the system that exposes data.
- **External/cloud**: A cloud or remote service (e.g. Slack, Google Drive, a REST API, Notion) that the user configures (credentials, endpoint, workspace, etc.).`,
  },
  {
    id: 'capabilities',
    title: 'Capabilities',
    content: `- **Read**: Ingest or sync data from the connection into the knowledge graph(s). For external sources, we first **extract and localize** the data in a format that involves the bare minimum transformation—ideally none. How that localized data gets into the graph is defined via **Types** (see below).
- **Write**: Update or sync data back to the connection (e.g. push notes, sync state). Connections are inherently read+write capable; permissions and UX control which of read/write (or both) are allowed for a given connection or tool.`,
  },
  {
    id: 'what-is-not-a-connection',
    title: 'What is not a connection',
    content: `- **Neo4j** is the **built-in graph database**. It is where graph data lives inside the app, not an external “source” in the connection sense. It does **not** fit the definition of a connection.
- **Which graphs (Neo4j DBs) an agent can use** is a **separate concept**: graph-level or knowledge-graph-level access control. That should be documented and designed alongside the permission system but under a different heading (e.g. “Graph access” or “Knowledge graph access”), not under “Connections.”`,
  },
  {
    id: 'types',
    title: 'Types',
    content: `Getting data from a connection into the graph is governed by **Types**.

- **Type**: The user’s way to define **node (label) structures** for the graph—properties, indexes, and constraints. A Type describes a kind of node (e.g. Person, Location, Book).
- **Source**: A Type can have one or more **sources**. Each source binds to a **connection** and defines:
  - The **rule for import** (how to interpret or select data from that connection).
  - **Property mapping** (connection fields → node properties).

So: **Connection** (data source, read/write) → **Type** (node shape + optional sources) → **Source** (connection + import rule + property mapping) → **Graph**. A Type can source data from multiple connections; the Type and its sources define how that becomes graph nodes.`,
  },
  {
    id: 'permission-system',
    title: 'Permission system',
    content: `- **Connection type**: The kind of data source (e.g. Folder, Slack, Google Drive). Not Neo4j.
- **Connection**: A specific instance (e.g. “My Project Folder”, “Slack #general”, “Drive – Work”).
- **Tools** that operate on a connection are associated with a **connection type** and optionally a **connection** (instance). Permission hierarchy (in modes) remains: **category** → **connection type** → **connection** → **tool**, but only for tools that act on connections (data sources). Neo4j/graph tools are governed by **graph access** (and category), not by connection type/connection.`,
  },
  {
    id: 'summary',
    title: 'Summary',
    content: `- **Connections** = data sources (folder, app, cloud). Read: extract/localize with minimal transformation; path to graph is via **Types** (node structures) and **Source** (connection + import rule + property mapping). Write: sync back to the connection.
- **Neo4j** = built-in graph DB; not a connection. **Graph access** (which knowledge graphs agents can use) is a separate concept.`,
  },
]

docBodies['getting-started'] = `# Getting Started

## Run Cortex

Start the app from your terminal or by opening the application. The first time you open Cortex, you'll see the Home view.

## Main areas

- **Home** — Overview and quick access. Use the sidebar to switch views.
- **Chat** — Have conversations with the AI. Choose a model and start typing. Responses stream in and support markdown and code.
- **Settings** — Configure AI providers (e.g. Ollama, Anthropic), select models, and adjust appearance (theme).

## Next steps

- Read [What is Cortex?](vision) for the big picture.
- Open **Settings** to add a provider and pick a model, then try **Chat**.`
docSections['getting-started'] = [
  { id: 'getting-started', title: 'Getting Started', content: `` },
  {
    id: 'run-cortex',
    title: 'Run Cortex',
    content: `Start the app from your terminal or by opening the application. The first time you open Cortex, you'll see the Home view.`,
  },
  {
    id: 'main-areas',
    title: 'Main areas',
    content: `- **Home** — Overview and quick access. Use the sidebar to switch views.
- **Chat** — Have conversations with the AI. Choose a model and start typing. Responses stream in and support markdown and code.
- **Settings** — Configure AI providers (e.g. Ollama, Anthropic), select models, and adjust appearance (theme).`,
  },
  {
    id: 'next-steps',
    title: 'Next steps',
    content: `- Read [What is Cortex?](vision) for the big picture.
- Open **Settings** to add a provider and pick a model, then try **Chat**.`,
  },
]

docBodies['vision'] = `# What is Cortex?

Cortex is an AI-powered personal knowledge management system that transforms how you interact with your own data. It connects all your personal information (conversations, health metrics, activities, projects, places, and experiences) into a unified, intelligent platform that helps you understand patterns, surface insights, and maintain meaningful context across your entire digital life.

## Core Benefits

### Own Your Data Completely
- All data stored locally in human-readable formats (Markdown, JSON)
- Never locked into proprietary systems or cloud services
- Full control over what stays private and what you choose to share
- Your knowledge base travels with you, forever

### Privacy-First Intelligence
- AI processing happens locally on your machine by default
- You decide which tasks can use cloud AI based on your own privacy preferences
- Sensitive personal data never leaves your control unless you explicitly choose otherwise
- Flexibility to balance privacy, speed, and capability for each use case

### Active Knowledge Management
- Beyond passive storage, the system proactively surfaces patterns and connections
- AI agents notice insights you might miss and bring them to your attention
- User-driven exploration through natural language chat and visual interfaces
- Both modes working together: ask questions AND receive unprompted discoveries

### Transparent AI Understanding
- The graph database makes the AI's "mental model" visible and inspectable
- See exactly what relationships and context informed any suggestion
- Audit how the AI understands your data
- Correct misunderstandings by fixing source data or transformation logic
- No black-box AI decisions, everything is traceable and editable

## How It Works

### Local-First Architecture
Cortex is built on a foundation of **local-first computing**. Your data lives in open, portable formats on your own machine. The graph database acts as an intelligent index, completely disposable and rebuildable from your source files.

This means:
- Work offline whenever you want
- Complete data sovereignty
- Version control and backup on your terms
- No vendor lock-in, ever

### Intelligent Data Integration
The system connects multiple data sources while respecting the nature of each:
- **Local data** (notes, journals, documents) → Direct local storage
- **External services** (Strava, GitHub, health apps) → Sync to local, then index
- **The Integration Heuristic**: "Would I want to reference this in my Notes?"
  - Yes → Create a Markdown file (meaningful events, insights)
  - No → Store as structured data (metrics, logs, continuous streams)

### Flexible AI Processing
By default, AI analysis runs locally to preserve privacy. You have full control to:
- Keep sensitive data processing entirely local
- Use cloud AI for specific tasks where you want more capability or speed
- Define your own boundaries based on your use cases and comfort level
- Change these preferences at any time

### Progressive Evolution
Cortex starts simple and grows smarter over time:
- Begin with manual exploration through chat and visual interfaces
- System learns which patterns you care about
- Agents gradually automate repetitive insights
- Both the data model and the tooling improve continuously through use

## The Bigger Vision

Beyond being a personal knowledge tool, Cortex represents a new approach to AI-augmented development. The long-term goal is a system where:
- AI agents become co-developers, not just assistants
- New features emerge from conversational guidance
- The system improves its own architecture over time
- You focus on "what" and "why" while AI handles "how"

But first, we build an excellent manual experience that proves the value, then we automate what works.

---

*This vision guides all architectural and implementation decisions. When in doubt, return to these principles: data ownership, privacy by default, user agency, and transparent intelligence.*`
docSections['vision'] = [
  {
    id: 'what-is-cortex',
    title: 'What is Cortex?',
    content: `Cortex is an AI-powered personal knowledge management system that transforms how you interact with your own data. It connects all your personal information (conversations, health metrics, activities, projects, places, and experiences) into a unified, intelligent platform that helps you understand patterns, surface insights, and maintain meaningful context across your entire digital life.`,
  },
  { id: 'core-benefits', title: 'Core Benefits', content: `` },
  {
    id: 'own-your-data-completely',
    title: 'Own Your Data Completely',
    content: `- All data stored locally in human-readable formats (Markdown, JSON)
- Never locked into proprietary systems or cloud services
- Full control over what stays private and what you choose to share
- Your knowledge base travels with you, forever`,
  },
  {
    id: 'privacy-first-intelligence',
    title: 'Privacy-First Intelligence',
    content: `- AI processing happens locally on your machine by default
- You decide which tasks can use cloud AI based on your own privacy preferences
- Sensitive personal data never leaves your control unless you explicitly choose otherwise
- Flexibility to balance privacy, speed, and capability for each use case`,
  },
  {
    id: 'active-knowledge-management',
    title: 'Active Knowledge Management',
    content: `- Beyond passive storage, the system proactively surfaces patterns and connections
- AI agents notice insights you might miss and bring them to your attention
- User-driven exploration through natural language chat and visual interfaces
- Both modes working together: ask questions AND receive unprompted discoveries`,
  },
  {
    id: 'transparent-ai-understanding',
    title: 'Transparent AI Understanding',
    content: `- The graph database makes the AI's "mental model" visible and inspectable
- See exactly what relationships and context informed any suggestion
- Audit how the AI understands your data
- Correct misunderstandings by fixing source data or transformation logic
- No black-box AI decisions, everything is traceable and editable`,
  },
  { id: 'how-it-works', title: 'How It Works', content: `` },
  {
    id: 'local-first-architecture',
    title: 'Local-First Architecture',
    content: `Cortex is built on a foundation of **local-first computing**. Your data lives in open, portable formats on your own machine. The graph database acts as an intelligent index, completely disposable and rebuildable from your source files.

This means:
- Work offline whenever you want
- Complete data sovereignty
- Version control and backup on your terms
- No vendor lock-in, ever`,
  },
  {
    id: 'intelligent-data-integration',
    title: 'Intelligent Data Integration',
    content: `The system connects multiple data sources while respecting the nature of each:
- **Local data** (notes, journals, documents) → Direct local storage
- **External services** (Strava, GitHub, health apps) → Sync to local, then index
- **The Integration Heuristic**: "Would I want to reference this in my Notes?"
  - Yes → Create a Markdown file (meaningful events, insights)
  - No → Store as structured data (metrics, logs, continuous streams)`,
  },
  {
    id: 'flexible-ai-processing',
    title: 'Flexible AI Processing',
    content: `By default, AI analysis runs locally to preserve privacy. You have full control to:
- Keep sensitive data processing entirely local
- Use cloud AI for specific tasks where you want more capability or speed
- Define your own boundaries based on your use cases and comfort level
- Change these preferences at any time`,
  },
  {
    id: 'progressive-evolution',
    title: 'Progressive Evolution',
    content: `Cortex starts simple and grows smarter over time:
- Begin with manual exploration through chat and visual interfaces
- System learns which patterns you care about
- Agents gradually automate repetitive insights
- Both the data model and the tooling improve continuously through use`,
  },
  {
    id: 'the-bigger-vision',
    title: 'The Bigger Vision',
    content: `Beyond being a personal knowledge tool, Cortex represents a new approach to AI-augmented development. The long-term goal is a system where:
- AI agents become co-developers, not just assistants
- New features emerge from conversational guidance
- The system improves its own architecture over time
- You focus on "what" and "why" while AI handles "how"

But first, we build an excellent manual experience that proves the value, then we automate what works.

---

*This vision guides all architectural and implementation decisions. When in doubt, return to these principles: data ownership, privacy by default, user agency, and transparent intelligence.*`,
  },
]

/** Full markdown body for a doc. */
export function getDocBody(slug: string): string | undefined {
  return docBodies[slug]
}

/** Short summary for tooltips (from frontmatter). */
export function getDocSummary(slug: string): string | undefined {
  return userDocsManifest[slug]?.summary
}

/** Section content (markdown) for a doc; for modal or deep link. */
export function getDocSectionContent(
  slug: string,
  sectionId: string
): string | undefined {
  const list = docSections[slug]
  if (!list) return undefined
  const s = list.find(x => x.id === sectionId)
  return s?.content
}

/** Ordered list of slugs for TOC. */
export const userDocSlugs: string[] = ['concepts', 'getting-started', 'vision']
